
# [[main]]
#   name = "Blog"
#   pageRef = "posts"
#   weight = 10

# [[main]]
#   name = "About"
#   pageRef = "about"
#   weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/0xBB2b"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

# [[main]]
#   name = "Linkedin"
#   url = "https://www.linkedin.com/in/0xBB2b"
#   weight = 30
#   [main.params]
#     icon = "linkedin"
#     showName = false
#     target = "_blank"

[[main]]
  name = "Email"
  url = "mailto:2b@yorha.xyz"
  weight = 30
  [main.params]
    icon = "email"
    showName = false
    target = "_blank"

# [[main]]
#   identifier = "search"
#   weight = 99
#   [main.params]
#     action = "search"
#     icon = "search"

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"